#!/usr/bin/env python3
"""
DMG Capital — Kraken Paper Trading Executor
Reads signals from callingmarkets/signals portfolios.json
Executes rebalance via Kraken CLI paper trading engine

Usage:
  Paper trading:  python executor.py
  Live trading:   python executor.py --live
"""

import json
import os
import subprocess
import sys
import time
import logging
from datetime import datetime, timezone
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
SIGNALS_URL    = "portfolios.json"   # local file — generated by crypto_portfolio.py in same repo
PORTFOLIO_ID   = "crypto-rotation"
LOG_FILE       = Path("execution_log.jsonl")
DRIFT_THRESHOLD = 0.03   # rebalance if position weight drifts >3% from target
MIN_ORDER_USD   = 10.0   # skip positions below this value
SLEEP_BETWEEN   = 1.5    # seconds between Kraken CLI calls

# Paper state persistence — stored in repo so GitHub Actions survives between runs
PAPER_STATE_REPO = Path("paper_state.db")                                           # committed to repo
PAPER_STATE_CLI  = Path.home() / ".local/share/kraken-cli/paper.db"                # Linux (GitHub Actions)
PAPER_STATE_MAC  = Path.home() / "Library/Application Support/kraken-cli/paper.db" # macOS fallback

# Kraken CLI pair map — ticker → Kraken pair name
# Kraken CLI paper uses BTCUSD format (no slash)
PAIR_MAP = {
    "BTC":  "BTCUSD",
    "ETH":  "ETHUSD",
    "XRP":  "XRPUSD",
    "SOL":  "SOLUSD",
    "DOGE": "DOGEUSD",
    "ADA":  "ADAUSD",
    "TRX":  "TRXUSD",
    "AVAX": "AVAXUSD",
    "LINK": "LINKUSD",
    "BCH":  "BCHUSD",
    "PAXG": "PAXGUSD",
    "LTC":  "LTCUSD",
    "DOT":  "DOTUSD",
}

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("dmg-executor")

LIVE = "--live" in sys.argv
MODE = "LIVE" if LIVE else "PAPER"
CMD  = "order" if LIVE else "paper"

# ── Kraken CLI helpers ────────────────────────────────────────────────────────
def kraken(args: list[str]) -> dict:
    """Run a kraken CLI command and return parsed JSON output."""
    full_cmd = ["kraken", CMD] + args + ["--output", "json"]
    log.debug(f"CMD: {' '.join(full_cmd)}")

    # For live trading, credentials are passed via env by the workflow
    env = os.environ.copy()

    result = subprocess.run(full_cmd, capture_output=True, text=True, timeout=30, env=env)

    stderr = result.stderr.strip()
    stdout = result.stdout.strip()

    if result.returncode != 0:
        raise RuntimeError(f"Kraken CLI error: {stderr or stdout or 'no output'}")

    if not stdout:
        raise RuntimeError(f"Kraken CLI returned empty output. stderr: {stderr}")

    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        return {"raw": stdout}


def restore_paper_state():
    """Copy paper_state.json from repo into Kraken CLI's expected location, or init fresh."""
    PAPER_STATE_CLI.parent.mkdir(parents=True, exist_ok=True)

    if PAPER_STATE_REPO.exists():
        import shutil
        shutil.copy2(PAPER_STATE_REPO, PAPER_STATE_CLI)
        log.info(f"Restored paper state from repo → {PAPER_STATE_CLI}")
    else:
        # First run — initialise a fresh paper account with $100,000
        log.info("No saved paper state — initialising fresh paper account with $100,000...")
        result = subprocess.run(
            ["kraken", "paper", "init", "--balance", "100000", "--output", "json"],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            raise RuntimeError(f"kraken paper init failed: {result.stderr.strip() or result.stdout.strip()}")
        log.info("Paper account initialised ✓")


def backup_paper_state():
    """Copy Kraken CLI's paper state back into the repo so it can be committed."""
    if not PAPER_STATE_CLI.exists():
        log.warning("No paper state file found to back up")
        return
    import shutil
    shutil.copy2(PAPER_STATE_CLI, PAPER_STATE_REPO)
    log.info(f"Backed up paper state → {PAPER_STATE_REPO}")


def get_balances() -> dict[str, float]:
    """Return {ticker: usd_value} for all paper balances using kraken paper balance."""
    data = kraken(["balance"])
    balances = {}

    log.debug(f"Balance response: {json.dumps(data)[:500]}")

    # kraken paper balance returns dict-of-dicts:
    # {"mode":"paper", "balances": {"USD": {"available": 100000.0, "total": 100000.0}, "BTC": {...}}}
    raw_balances = data.get("balances") or {}

    if isinstance(raw_balances, dict):
        raw = {}
        for asset, info in raw_balances.items():
            asset_clean = asset.upper().replace("XBT", "BTC").replace("XXBT", "BTC")
            try:
                # Use "total" field (available + reserved)
                qty = float(info.get("total") or info.get("available") or 0)
            except (ValueError, TypeError):
                qty = 0
            if qty > 0:
                raw[asset_clean] = qty

        # USD is already in USD value
        if "USD" in raw:
            balances["USD"] = raw["USD"]

        # For crypto assets, convert qty → USD using live price
        for asset, qty in raw.items():
            if asset == "USD":
                continue
            price = get_price(asset)
            if price and qty > 0:
                usd_val = round(qty * price, 2)
                if usd_val > 0.01:
                    balances[asset] = usd_val
            else:
                log.warning(f"Could not price {asset} — skipping from balance")

    elif isinstance(raw_balances, list):
        # Fallback: list format [{"asset": "USD", "balance": "100000.00"}, ...]
        raw = {}
        for item in raw_balances:
            asset = (item.get("asset") or "").upper().replace("XBT","BTC")
            try:
                qty = float(item.get("total") or item.get("balance") or 0)
            except (ValueError, TypeError):
                qty = 0
            if asset and qty > 0:
                raw[asset] = qty
        if "USD" in raw:
            balances["USD"] = raw["USD"]
        for asset, qty in raw.items():
            if asset == "USD":
                continue
            price = get_price(asset)
            if price and qty > 0:
                usd_val = round(qty * price, 2)
                if usd_val > 0.01:
                    balances[asset] = usd_val

    # Fresh account fallback
    if not balances:
        log.warning("No balances found — assuming fresh paper account with $100,000 USD")
        balances["USD"] = 100000.0

    return balances


def get_total_balance(balances: dict[str, float]) -> float:
    return sum(balances.values())


def get_price(ticker: str) -> float | None:
    """Fetch live price via `kraken ticker PAIR` — public endpoint, no auth needed."""
    pair = PAIR_MAP.get(ticker)
    if not pair:
        log.warning(f"No pair mapping for {ticker}")
        return None
    full_cmd = ["kraken", "ticker", pair, "--output", "json"]
    result = subprocess.run(full_cmd, capture_output=True, text=True, timeout=30)
    raw = result.stdout.strip()

    if result.returncode != 0:
        log.warning(f"Price fetch failed for {ticker}: {result.stderr.strip()}")
        return None

    try:
        data = json.loads(raw)
        # Response format: {"XXBTZUSD": {"c": ["76596.20", "0.001"], "a": [...], ...}}
        # The key is Kraken's internal pair name — just grab the first (only) key's value
        for key, val in data.items():
            if isinstance(val, dict):
                # c = last trade [price, volume] — most accurate
                c = val.get("c")
                if c and len(c) > 0:
                    return float(c[0])
                # fallback: ask price
                a = val.get("a")
                if a and len(a) > 0:
                    return float(a[0])
        log.warning(f"Could not parse price for {ticker} from: {raw[:200]}")
        return None
    except (json.JSONDecodeError, TypeError, ValueError) as e:
        log.warning(f"Price parse error for {ticker}: {e} | raw: {raw[:200]}")
        return None


def place_sell(ticker: str, amount_usd: float) -> dict:
    pair = PAIR_MAP.get(ticker)
    if not pair:
        raise ValueError(f"No pair for {ticker}")
    price = get_price(ticker)
    if not price:
        raise ValueError(f"Could not get price for {ticker}")
    qty = round(amount_usd / price, 8)
    log.info(f"  SELL {ticker}  qty={qty}  ~${amount_usd:,.2f}")
    # kraken paper sell BTCUSD <qty> --type market
    return kraken(["sell", pair, str(qty), "--type", "market"])


def place_buy(ticker: str, amount_usd: float) -> dict:
    pair = PAIR_MAP.get(ticker)
    if not pair:
        raise ValueError(f"No pair for {ticker}")
    price = get_price(ticker)
    if not price:
        raise ValueError(f"Could not get price for {ticker}")
    qty = round(amount_usd / price, 8)
    log.info(f"  BUY  {ticker}  qty={qty}  ~${amount_usd:,.2f}")
    # kraken paper buy BTCUSD <qty> --type market
    return kraken(["buy", pair, str(qty), "--type", "market"])


# ── Signal fetch ──────────────────────────────────────────────────────────────
def fetch_signals() -> dict:
    """Read portfolios.json from local file (generated by signal engine in same repo)."""
    path = Path(SIGNALS_URL)
    if not path.exists():
        raise FileNotFoundError(f"portfolios.json not found — has the signal engine run yet?")
    log.info(f"Reading signals from local portfolios.json...")
    with open(path) as f:
        data = json.load(f)
    portfolios = data.get("portfolios", [])
    p = next((x for x in portfolios if x["id"] == PORTFOLIO_ID), None)
    if not p:
        raise ValueError(f"Portfolio '{PORTFOLIO_ID}' not found in portfolios.json")
    return p


# ── Rebalance logic ───────────────────────────────────────────────────────────
def compute_rebalance(
    current_balances: dict[str, float],
    target_tickers: list[str],
    total_usd: float,
) -> tuple[list[tuple], list[tuple]]:
    """
    Returns (sells, buys) as lists of (ticker, usd_amount).
    Sells first, then buys with proceeds.
    """
    n = len(target_tickers)
    target_weight = 1.0 / n if n > 0 else 0
    target_usd    = {t: total_usd * target_weight for t in target_tickers}

    sells, buys = [], []

    # Assets to sell — currently held but not in target
    for ticker, usd_val in current_balances.items():
        if ticker == "USD" or usd_val < MIN_ORDER_USD:
            continue
        if ticker not in target_tickers:
            sells.append((ticker, usd_val))
        else:
            # Check drift — if significantly overweight/underweight, rebalance
            target = target_usd.get(ticker, 0)
            drift  = abs(usd_val - target) / total_usd
            if drift > DRIFT_THRESHOLD and abs(usd_val - target) > MIN_ORDER_USD:
                if usd_val > target:
                    sells.append((ticker, usd_val - target))

    # Assets to buy — in target but not currently held (or underweight)
    for ticker in target_tickers:
        current = current_balances.get(ticker, 0)
        target  = target_usd[ticker]
        diff    = target - current
        if diff > MIN_ORDER_USD:
            buys.append((ticker, diff))

    return sells, buys


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    now = datetime.now(timezone.utc)
    log.info(f"{'='*52}")
    log.info(f"DMG Capital Executor — {MODE} mode")
    log.info(f"Time: {now.isoformat()}")
    log.info(f"{'='*52}")

    if LIVE:
        log.warning("⚠ LIVE MODE — real orders will be placed")
        confirm = input("Type YES to continue: ")
        if confirm.strip() != "YES":
            log.info("Aborted.")
            return

    # 1. Fetch signals
    try:
        portfolio = fetch_signals()
    except Exception as e:
        log.error(f"Failed to fetch signals: {e}")
        sys.exit(1)

    signals    = portfolio.get("current_signals", {})
    btc_signal = signals.get("BTC", "SELL")
    paxg_signal= signals.get("PAXG", "SELL")
    generated  = portfolio.get("generated", "unknown")

    log.info(f"Signals from: {generated}")
    log.info(f"BTC gate:     {btc_signal}")
    log.info(f"PAXG signal:  {paxg_signal}")

    # 2. Determine target allocation
    if btc_signal == "BUY":
        # Gate open — equal weight all BUY signals in current top-10 universe
        universe = list(set(
            t for yr in [
                ["BTC","ETH","XRP","SOL","DOGE","ADA","TRX","AVAX","LINK","BCH"]
            ] for t in yr
        ))
        target_tickers = [
            t for t in universe
            if signals.get(t) == "BUY" and t not in ("BTC", "PAXG")
        ]
        # BTC itself — include if in BUY
        if btc_signal == "BUY":
            target_tickers = [t for t in signals if signals[t] == "BUY" and t != "PAXG"]
        defensive = None
        log.info(f"Gate OPEN — target: {', '.join(sorted(target_tickers))}")
    else:
        # Gate closed — PAXG or USDT
        if paxg_signal == "BUY":
            target_tickers = ["PAXG"]
            defensive = "PAXG"
            log.info("Gate CLOSED — defensive: PAXG")
        else:
            target_tickers = []
            defensive = "USDT"
            log.info("Gate CLOSED — defensive: USDT (cash)")

    # 3. Restore paper state from repo, then get balances
    if not LIVE:
        restore_paper_state()

    try:
        balances = get_balances()
        total    = get_total_balance(balances)
        log.info(f"Current balance: ${total:,.2f}")
        for t, v in balances.items():
            log.info(f"  {t}: ${v:,.2f}")
    except Exception as e:
        log.error(f"Failed to get balances: {e}")
        sys.exit(1)

    if total < MIN_ORDER_USD:
        log.error(f"Total balance ${total:.2f} is below minimum ${MIN_ORDER_USD}")
        sys.exit(1)

    # 4. Compute rebalance
    if not target_tickers:
        # Move everything to USD (sell all non-USD)
        sells = [(t, v) for t, v in balances.items() if t != "USD" and v > MIN_ORDER_USD]
        buys  = []
        log.info("Target is 100% USDT — selling all positions")
    else:
        sells, buys = compute_rebalance(balances, target_tickers, total)

    if not sells and not buys:
        log.info("✓ No rebalance needed — portfolio already matches target")
        if not LIVE:
            backup_paper_state()
        _log_execution(now, signals, target_tickers, defensive, [], [], total, "NO_CHANGE")
        return

    log.info(f"Sells: {len(sells)}  Buys: {len(buys)}")

    # 5. Execute sells first
    sell_results = []
    for ticker, usd_val in sells:
        try:
            result = place_sell(ticker, usd_val)
            sell_results.append({"ticker": ticker, "usd": usd_val, "status": "ok", "result": result})
            time.sleep(SLEEP_BETWEEN)
        except Exception as e:
            log.error(f"  SELL {ticker} failed: {e}")
            sell_results.append({"ticker": ticker, "usd": usd_val, "status": "error", "error": str(e)})

    # Wait for sells to settle
    if sells:
        log.info("Waiting 3s for sells to settle...")
        time.sleep(3)

    # 6. Refresh balance after sells
    try:
        balances = get_balances()
        total    = get_total_balance(balances)
        log.info(f"Post-sell balance: ${total:,.2f}")
    except Exception as e:
        log.warning(f"Could not refresh balance: {e}")

    # 7. Execute buys — equal weight with available funds
    buy_results = []
    if buys and target_tickers:
        n = len(target_tickers)
        usd_per = total / n
        for ticker in target_tickers:
            if usd_per < MIN_ORDER_USD:
                log.warning(f"  Skipping {ticker} — allocation ${usd_per:.2f} below minimum")
                continue
            try:
                result = place_buy(ticker, usd_per)
                buy_results.append({"ticker": ticker, "usd": usd_per, "status": "ok", "result": result})
                time.sleep(SLEEP_BETWEEN)
            except Exception as e:
                log.error(f"  BUY {ticker} failed: {e}")
                buy_results.append({"ticker": ticker, "usd": usd_per, "status": "error", "error": str(e)})

    # 8. Back up paper state to repo so it survives next GitHub Actions run
    if not LIVE:
        backup_paper_state()

    # 9. Summary
    log.info(f"{'='*52}")
    log.info(f"Execution complete")
    log.info(f"  Sells: {sum(1 for r in sell_results if r['status']=='ok')}/{len(sell_results)}")
    log.info(f"  Buys:  {sum(1 for r in buy_results  if r['status']=='ok')}/{len(buy_results)}")
    log.info(f"{'='*52}")

    # 9. Write log
    _log_execution(now, signals, target_tickers, defensive,
                   sell_results, buy_results, total, "EXECUTED")


def _log_execution(now, signals, target, defensive, sells, buys, total, status):
    entry = {
        "timestamp":      now.isoformat(),
        "mode":           MODE,
        "status":         status,
        "btc_signal":     signals.get("BTC"),
        "paxg_signal":    signals.get("PAXG"),
        "defensive":      defensive,
        "target_tickers": target,
        "total_usd":      round(total, 2),
        "sells":          sells,
        "buys":           buys,
    }
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")
    log.info(f"✓ Logged to {LOG_FILE}")


if __name__ == "__main__":
    main()
