#!/usr/bin/env python3
"""
DMG Capital — Kraken Paper Trading Executor
Reads signals from callingmarkets/signals portfolios.json
Executes rebalance via Kraken CLI paper trading engine

Usage:
  Paper trading:  python executor.py
  Live trading:   python executor.py --live
"""

import json
import subprocess
import sys
import time
import logging
from datetime import datetime, timezone
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
SIGNALS_URL    = "portfolios.json"   # local file — generated by crypto_portfolio.py in same repo
PORTFOLIO_ID   = "crypto-rotation"
LOG_FILE       = Path("execution_log.jsonl")
DRIFT_THRESHOLD = 0.03   # rebalance if position weight drifts >3% from target
MIN_ORDER_USD   = 10.0   # skip positions below this value
SLEEP_BETWEEN   = 1.5    # seconds between Kraken CLI calls

# Kraken CLI pair map — ticker → Kraken pair name
PAIR_MAP = {
    "BTC":  "BTC/USD",
    "ETH":  "ETH/USD",
    "XRP":  "XRP/USD",
    "SOL":  "SOL/USD",
    "DOGE": "DOGE/USD",
    "ADA":  "ADA/USD",
    "TRX":  "TRX/USD",
    "AVAX": "AVAX/USD",
    "LINK": "LINK/USD",
    "BCH":  "BCH/USD",
    "PAXG": "PAXG/USD",
    "LTC":  "LTC/USD",
    "DOT":  "DOT/USD",
}

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("dmg-executor")

LIVE = "--live" in sys.argv
MODE = "LIVE" if LIVE else "PAPER"
CMD  = "order" if LIVE else "paper"

# ── Kraken CLI helpers ────────────────────────────────────────────────────────
def kraken(args: list[str]) -> dict:
    """Run a kraken CLI command and return parsed JSON output."""
    full_cmd = ["kraken", CMD] + args + ["--output", "json"]
    log.debug(f"CMD: {' '.join(full_cmd)}")
    result = subprocess.run(full_cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"Kraken CLI error: {result.stderr.strip()}")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"raw": result.stdout.strip()}


def get_balances() -> dict[str, float]:
    """Return {ticker: usd_value} for all non-zero balances."""
    data = kraken(["balance"])
    balances = {}
    # CLI returns list of {asset, balance, usd_value} or similar
    for item in data.get("balances", []):
        ticker = item.get("asset", "").replace("XBT", "BTC")
        usd    = float(item.get("usd_value", 0))
        if usd > 0.01:
            balances[ticker] = usd
    return balances


def get_total_balance(balances: dict[str, float]) -> float:
    return sum(balances.values())


def get_price(ticker: str) -> float | None:
    pair = PAIR_MAP.get(ticker)
    if not pair:
        log.warning(f"No pair mapping for {ticker}")
        return None
    data = kraken(["price", pair])
    price = data.get("price") or data.get("last")
    return float(price) if price else None


def place_sell(ticker: str, amount_usd: float) -> dict:
    pair = PAIR_MAP.get(ticker)
    if not pair:
        raise ValueError(f"No pair for {ticker}")
    price = get_price(ticker)
    if not price:
        raise ValueError(f"Could not get price for {ticker}")
    qty = round(amount_usd / price, 8)
    log.info(f"  SELL {ticker}  qty={qty}  ~${amount_usd:,.2f}")
    return kraken(["sell", pair, str(qty), "--type", "market"])


def place_buy(ticker: str, amount_usd: float) -> dict:
    pair = PAIR_MAP.get(ticker)
    if not pair:
        raise ValueError(f"No pair for {ticker}")
    price = get_price(ticker)
    if not price:
        raise ValueError(f"Could not get price for {ticker}")
    qty = round(amount_usd / price, 8)
    log.info(f"  BUY  {ticker}  qty={qty}  ~${amount_usd:,.2f}")
    return kraken(["buy", pair, str(qty), "--type", "market"])


# ── Signal fetch ──────────────────────────────────────────────────────────────
def fetch_signals() -> dict:
    """Read portfolios.json from local file (generated by signal engine in same repo)."""
    path = Path(SIGNALS_URL)
    if not path.exists():
        raise FileNotFoundError(f"portfolios.json not found — has the signal engine run yet?")
    log.info(f"Reading signals from local portfolios.json...")
    with open(path) as f:
        data = json.load(f)
    portfolios = data.get("portfolios", [])
    p = next((x for x in portfolios if x["id"] == PORTFOLIO_ID), None)
    if not p:
        raise ValueError(f"Portfolio '{PORTFOLIO_ID}' not found in portfolios.json")
    return p


# ── Rebalance logic ───────────────────────────────────────────────────────────
def compute_rebalance(
    current_balances: dict[str, float],
    target_tickers: list[str],
    total_usd: float,
) -> tuple[list[tuple], list[tuple]]:
    """
    Returns (sells, buys) as lists of (ticker, usd_amount).
    Sells first, then buys with proceeds.
    """
    n = len(target_tickers)
    target_weight = 1.0 / n if n > 0 else 0
    target_usd    = {t: total_usd * target_weight for t in target_tickers}

    sells, buys = [], []

    # Assets to sell — currently held but not in target
    for ticker, usd_val in current_balances.items():
        if ticker == "USD" or usd_val < MIN_ORDER_USD:
            continue
        if ticker not in target_tickers:
            sells.append((ticker, usd_val))
        else:
            # Check drift — if significantly overweight/underweight, rebalance
            target = target_usd.get(ticker, 0)
            drift  = abs(usd_val - target) / total_usd
            if drift > DRIFT_THRESHOLD and abs(usd_val - target) > MIN_ORDER_USD:
                if usd_val > target:
                    sells.append((ticker, usd_val - target))

    # Assets to buy — in target but not currently held (or underweight)
    for ticker in target_tickers:
        current = current_balances.get(ticker, 0)
        target  = target_usd[ticker]
        diff    = target - current
        if diff > MIN_ORDER_USD:
            buys.append((ticker, diff))

    return sells, buys


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    now = datetime.now(timezone.utc)
    log.info(f"{'='*52}")
    log.info(f"DMG Capital Executor — {MODE} mode")
    log.info(f"Time: {now.isoformat()}")
    log.info(f"{'='*52}")

    if LIVE:
        log.warning("⚠ LIVE MODE — real orders will be placed")
        confirm = input("Type YES to continue: ")
        if confirm.strip() != "YES":
            log.info("Aborted.")
            return

    # 1. Fetch signals
    try:
        portfolio = fetch_signals()
    except Exception as e:
        log.error(f"Failed to fetch signals: {e}")
        sys.exit(1)

    signals    = portfolio.get("current_signals", {})
    btc_signal = signals.get("BTC", "SELL")
    paxg_signal= signals.get("PAXG", "SELL")
    generated  = portfolio.get("generated", "unknown")

    log.info(f"Signals from: {generated}")
    log.info(f"BTC gate:     {btc_signal}")
    log.info(f"PAXG signal:  {paxg_signal}")

    # 2. Determine target allocation
    if btc_signal == "BUY":
        # Gate open — equal weight all BUY signals in current top-10 universe
        universe = list(set(
            t for yr in [
                ["BTC","ETH","XRP","SOL","DOGE","ADA","TRX","AVAX","LINK","BCH"]
            ] for t in yr
        ))
        target_tickers = [
            t for t in universe
            if signals.get(t) == "BUY" and t not in ("BTC", "PAXG")
        ]
        # BTC itself — include if in BUY
        if btc_signal == "BUY":
            target_tickers = [t for t in signals if signals[t] == "BUY" and t != "PAXG"]
        defensive = None
        log.info(f"Gate OPEN — target: {', '.join(sorted(target_tickers))}")
    else:
        # Gate closed — PAXG or USDT
        if paxg_signal == "BUY":
            target_tickers = ["PAXG"]
            defensive = "PAXG"
            log.info("Gate CLOSED — defensive: PAXG")
        else:
            target_tickers = []
            defensive = "USDT"
            log.info("Gate CLOSED — defensive: USDT (cash)")

    # 3. Get current balances
    try:
        balances = get_balances()
        total    = get_total_balance(balances)
        log.info(f"Current balance: ${total:,.2f}")
        for t, v in balances.items():
            log.info(f"  {t}: ${v:,.2f}")
    except Exception as e:
        log.error(f"Failed to get balances: {e}")
        sys.exit(1)

    if total < MIN_ORDER_USD:
        log.error(f"Total balance ${total:.2f} is below minimum ${MIN_ORDER_USD}")
        sys.exit(1)

    # 4. Compute rebalance
    if not target_tickers:
        # Move everything to USD (sell all non-USD)
        sells = [(t, v) for t, v in balances.items() if t != "USD" and v > MIN_ORDER_USD]
        buys  = []
        log.info("Target is 100% USDT — selling all positions")
    else:
        sells, buys = compute_rebalance(balances, target_tickers, total)

    if not sells and not buys:
        log.info("✓ No rebalance needed — portfolio already matches target")
        _log_execution(now, signals, target_tickers, defensive, [], [], total, "NO_CHANGE")
        return

    log.info(f"Sells: {len(sells)}  Buys: {len(buys)}")

    # 5. Execute sells first
    sell_results = []
    for ticker, usd_val in sells:
        try:
            result = place_sell(ticker, usd_val)
            sell_results.append({"ticker": ticker, "usd": usd_val, "status": "ok", "result": result})
            time.sleep(SLEEP_BETWEEN)
        except Exception as e:
            log.error(f"  SELL {ticker} failed: {e}")
            sell_results.append({"ticker": ticker, "usd": usd_val, "status": "error", "error": str(e)})

    # Wait for sells to settle
    if sells:
        log.info("Waiting 3s for sells to settle...")
        time.sleep(3)

    # 6. Refresh balance after sells
    try:
        balances = get_balances()
        total    = get_total_balance(balances)
        log.info(f"Post-sell balance: ${total:,.2f}")
    except Exception as e:
        log.warning(f"Could not refresh balance: {e}")

    # 7. Execute buys — equal weight with available funds
    buy_results = []
    if buys and target_tickers:
        n = len(target_tickers)
        usd_per = total / n
        for ticker in target_tickers:
            if usd_per < MIN_ORDER_USD:
                log.warning(f"  Skipping {ticker} — allocation ${usd_per:.2f} below minimum")
                continue
            try:
                result = place_buy(ticker, usd_per)
                buy_results.append({"ticker": ticker, "usd": usd_per, "status": "ok", "result": result})
                time.sleep(SLEEP_BETWEEN)
            except Exception as e:
                log.error(f"  BUY {ticker} failed: {e}")
                buy_results.append({"ticker": ticker, "usd": usd_per, "status": "error", "error": str(e)})

    # 8. Summary
    log.info(f"{'='*52}")
    log.info(f"Execution complete")
    log.info(f"  Sells: {sum(1 for r in sell_results if r['status']=='ok')}/{len(sell_results)}")
    log.info(f"  Buys:  {sum(1 for r in buy_results  if r['status']=='ok')}/{len(buy_results)}")
    log.info(f"{'='*52}")

    # 9. Write log
    _log_execution(now, signals, target_tickers, defensive,
                   sell_results, buy_results, total, "EXECUTED")


def _log_execution(now, signals, target, defensive, sells, buys, total, status):
    entry = {
        "timestamp":      now.isoformat(),
        "mode":           MODE,
        "status":         status,
        "btc_signal":     signals.get("BTC"),
        "paxg_signal":    signals.get("PAXG"),
        "defensive":      defensive,
        "target_tickers": target,
        "total_usd":      round(total, 2),
        "sells":          sells,
        "buys":           buys,
    }
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")
    log.info(f"✓ Logged to {LOG_FILE}")


if __name__ == "__main__":
    main()
