#!/usr/bin/env python3
"""
DMG Capital — Kraken Paper Trading Executor
Reads signals from portfolios.json (same repo, generated by crypto_portfolio.py)
Executes minimal rebalance via Kraken CLI paper trading

Usage:
  Paper trading:  python executor.py
  Live trading:   python executor.py --live
"""

import json
import os
import subprocess
import sys
import time
import logging
from datetime import datetime, timezone
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
SIGNALS_URL      = "portfolios.json"   # local file — generated by signal engine in same repo
PORTFOLIO_ID     = "crypto-rotation"
LOG_FILE         = Path("execution_log.jsonl")
DRIFT_THRESHOLD  = 0.03    # only rebalance if position drifts >3% of total portfolio
MIN_ORDER_USD    = 10.0    # skip orders below this value
SLEEP_BETWEEN    = 1.5     # seconds between Kraken CLI calls

# Paper state persistence — store db in repo so GitHub Actions survives between runs
PAPER_STATE_REPO = Path("paper_state.db")
PAPER_STATE_CANDIDATES = [
    Path.home() / ".local/share/kraken-cli/paper.db",                # Linux (GitHub Actions)
    Path.home() / ".local/share/kraken/paper.db",                    # Linux alt
    Path.home() / "Library/Application Support/kraken-cli/paper.db", # macOS
    Path.home() / ".config/kraken/paper.db",                         # Linux config
    Path.home() / ".config/kraken-cli/paper.db",                     # Linux config alt
]

# Kraken CLI pair map — ticker → Kraken paper pair name (no slash)
PAIR_MAP = {
    "BTC":  "BTCUSD",
    "ETH":  "ETHUSD",
    "XRP":  "XRPUSD",
    "SOL":  "SOLUSD",
    "DOGE": "DOGEUSD",
    "ADA":  "ADAUSD",
    "TRX":  "TRXUSD",
    "AVAX": "AVAXUSD",
    "LINK": "LINKUSD",
    "BCH":  "BCHUSD",
    "PAXG": "PAXGUSD",
    "LTC":  "LTCUSD",
    "DOT":  "DOTUSD",
}

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("dmg-executor")

LIVE = "--live" in sys.argv
MODE = "LIVE" if LIVE else "PAPER"
CMD  = "order" if LIVE else "paper"

# ── Kraken CLI ────────────────────────────────────────────────────────────────
def kraken(args: list[str]) -> dict:
    """Run a kraken CLI command, return parsed JSON."""
    full_cmd = ["kraken", CMD] + args + ["--output", "json"]
    log.debug(f"CMD: {' '.join(full_cmd)}")
    env = os.environ.copy()
    result = subprocess.run(full_cmd, capture_output=True, text=True, timeout=30, env=env)
    stdout = result.stdout.strip()
    stderr = result.stderr.strip()
    if result.returncode != 0:
        raise RuntimeError(f"Kraken CLI error: {stderr or stdout or 'no output'}")
    if not stdout:
        raise RuntimeError(f"Kraken CLI empty output. stderr: {stderr}")
    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        return {"raw": stdout}


def get_price(ticker: str) -> float | None:
    """Fetch live price via `kraken ticker PAIR` — public endpoint, no auth needed."""
    pair = PAIR_MAP.get(ticker)
    if not pair:
        log.warning(f"No pair mapping for {ticker}")
        return None
    full_cmd = ["kraken", "ticker", pair, "--output", "json"]
    result = subprocess.run(full_cmd, capture_output=True, text=True, timeout=30)
    raw = result.stdout.strip()
    if result.returncode != 0:
        log.warning(f"Price fetch failed for {ticker}: {result.stderr.strip()}")
        return None
    try:
        data = json.loads(raw)
        # Response: {"XXBTZUSD": {"c": ["76596.20", "0.001"], "a": [...], ...}}
        # Iterate over whatever internal key Kraken uses — grab first dict value
        for key, val in data.items():
            if isinstance(val, dict):
                c = val.get("c")   # last trade close [price, volume]
                if c and len(c) > 0:
                    return float(c[0])
                a = val.get("a")   # ask [price, wholeLotVol, lotVol]
                if a and len(a) > 0:
                    return float(a[0])
        log.warning(f"Could not parse price for {ticker} from: {raw[:200]}")
        return None
    except (json.JSONDecodeError, TypeError, ValueError) as e:
        log.warning(f"Price parse error for {ticker}: {e}")
        return None


def get_balances() -> dict[str, float]:
    """Return {ticker: usd_value} for all paper balances."""
    data = kraken(["balance"])
    log.debug(f"Balance response: {json.dumps(data)[:500]}")
    balances = {}

    raw_balances = data.get("balances") or {}

    if isinstance(raw_balances, dict):
        raw = {}
        for asset, info in raw_balances.items():
            asset_clean = asset.upper().replace("XBT", "BTC").replace("XXBT", "BTC")
            try:
                qty = float(info.get("total") or info.get("available") or 0)
            except (ValueError, TypeError):
                qty = 0
            if qty > 0:
                raw[asset_clean] = qty

        if "USD" in raw:
            balances["USD"] = raw["USD"]

        for asset, qty in raw.items():
            if asset == "USD":
                continue
            price = get_price(asset)
            if price and qty > 0:
                usd_val = round(qty * price, 2)
                if usd_val > 0.01:
                    balances[asset] = usd_val
            else:
                log.warning(f"Could not price {asset} — skipping")

    elif isinstance(raw_balances, list):
        raw = {}
        for item in raw_balances:
            asset = (item.get("asset") or "").upper().replace("XBT", "BTC")
            try:
                qty = float(item.get("total") or item.get("balance") or 0)
            except (ValueError, TypeError):
                qty = 0
            if asset and qty > 0:
                raw[asset] = qty
        if "USD" in raw:
            balances["USD"] = raw["USD"]
        for asset, qty in raw.items():
            if asset == "USD":
                continue
            price = get_price(asset)
            if price and qty > 0:
                usd_val = round(qty * price, 2)
                if usd_val > 0.01:
                    balances[asset] = usd_val

    if not balances:
        log.warning("No balances found — assuming fresh paper account with $100,000 USD")
        balances["USD"] = 100000.0

    return balances


def get_total_balance(balances: dict[str, float]) -> float:
    return sum(balances.values())


def place_sell(ticker: str, amount_usd: float) -> dict:
    pair  = PAIR_MAP.get(ticker)
    if not pair:
        raise ValueError(f"No pair for {ticker}")
    price = get_price(ticker)
    if not price:
        raise ValueError(f"Could not get price for {ticker}")
    qty = round(amount_usd / price, 8)
    log.info(f"  SELL {ticker}  qty={qty}  ~${amount_usd:,.2f}")
    return kraken(["sell", pair, str(qty), "--type", "market"])


def place_buy(ticker: str, amount_usd: float) -> dict:
    pair  = PAIR_MAP.get(ticker)
    if not pair:
        raise ValueError(f"No pair for {ticker}")
    price = get_price(ticker)
    if not price:
        raise ValueError(f"Could not get price for {ticker}")
    qty = round(amount_usd / price, 8)
    log.info(f"  BUY  {ticker}  qty={qty}  ~${amount_usd:,.2f}")
    return kraken(["buy", pair, str(qty), "--type", "market"])


# ── Paper state ───────────────────────────────────────────────────────────────
def _find_cli_state() -> Path | None:
    for candidate in PAPER_STATE_CANDIDATES:
        if candidate.exists():
            log.debug(f"Found paper state at: {candidate}")
            return candidate
    for match in Path.home().glob("**/paper.db"):
        log.debug(f"Found paper state via glob: {match}")
        return match
    return None


def restore_paper_state():
    import shutil
    if not PAPER_STATE_REPO.exists():
        log.info("No saved paper state — initialising fresh paper account with $100,000...")
        result = subprocess.run(
            ["kraken", "paper", "init", "--balance", "100000", "--output", "json"],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            raise RuntimeError(f"kraken paper init failed: {result.stderr.strip()}")
        log.info("Paper account initialised ✓")
        return
    restored = False
    for dest in PAPER_STATE_CANDIDATES:
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(PAPER_STATE_REPO, dest)
            log.info(f"Restored paper state → {dest}")
            restored = True
        except Exception as e:
            log.debug(f"Could not restore to {dest}: {e}")
    if not restored:
        log.warning("Could not restore paper state — initing fresh account")
        subprocess.run(["kraken", "paper", "init", "--balance", "100000"], capture_output=True)


def backup_paper_state():
    import shutil
    src = _find_cli_state()
    if not src:
        log.warning("Paper state db not found. Searched:")
        for c in PAPER_STATE_CANDIDATES:
            log.warning(f"  {'✓' if c.exists() else '✗'} {c}")
        return
    shutil.copy2(src, PAPER_STATE_REPO)
    log.info(f"Backed up paper state: {src} → {PAPER_STATE_REPO}")


# ── Signal fetch ──────────────────────────────────────────────────────────────
def fetch_signals() -> dict:
    path = Path(SIGNALS_URL)
    if not path.exists():
        raise FileNotFoundError(f"portfolios.json not found — has the signal engine run yet?")
    log.info("Reading signals from local portfolios.json...")
    with open(path) as f:
        data = json.load(f)
    portfolios = data.get("portfolios", [])
    p = next((x for x in portfolios if x["id"] == PORTFOLIO_ID), None)
    if not p:
        raise ValueError(f"Portfolio '{PORTFOLIO_ID}' not found in portfolios.json")
    return p


# ── Rebalance ─────────────────────────────────────────────────────────────────
def compute_rebalance(
    current_balances: dict[str, float],
    target_tickers: list[str],
    total_usd: float,
) -> tuple[list[tuple], list[tuple]]:
    """
    Minimal self-funding rebalance:

    - Assets that flipped SELL  → sell full position; proceeds fund new buys
    - Assets newly in BUY       → buy at equal-weight; funded by trimming
                                   overweight positions (most overweight first)
    - Assets still in target    → trim/top-up only if drift > DRIFT_THRESHOLD
    - All trades self-funded    → no idle cash left behind
    """
    n = len(target_tickers)
    if n == 0:
        return [], []

    target_usd   = {t: total_usd / n for t in target_tickers}
    sells, buys  = [], []
    held_tickers = {t for t, v in current_balances.items()
                    if t != "USD" and v >= MIN_ORDER_USD}

    # ── 1. Flipped SELL — liquidate fully ────────────────────────────────────
    flipped_sell  = held_tickers - set(target_tickers)
    sell_proceeds = 0.0
    for ticker in sorted(flipped_sell):
        val = current_balances[ticker]
        sells.append((ticker, val))
        sell_proceeds += val
        log.info(f"  {ticker}: SELL full ${val:,.2f} (signal → SELL)")

    # ── 2. New BUY signals — calculate funding gap ───────────────────────────
    new_buys     = sorted(set(target_tickers) - held_tickers)
    new_buy_cost = sum(target_usd[t] for t in new_buys)

    for ticker in new_buys:
        buys.append((ticker, target_usd[ticker]))
        log.info(f"  {ticker}: BUY new position ${target_usd[ticker]:,.2f} (signal → BUY)")

    # ── 3. Fund gap by trimming most overweight positions ────────────────────
    funding_gap   = max(0.0, new_buy_cost - sell_proceeds)
    remaining_gap = funding_gap
    still_held    = sorted(held_tickers & set(target_tickers))

    # Sort by excess descending — trim fattest positions first
    overweights = []
    for ticker in still_held:
        current_val = current_balances[ticker]
        target      = target_usd[ticker]
        excess      = current_val - target
        drift_pct   = (current_val - target) / total_usd
        overweights.append((ticker, current_val, target, excess, drift_pct))
    overweights.sort(key=lambda x: x[3], reverse=True)

    for ticker, current_val, target, excess, drift_pct in overweights:
        if remaining_gap > MIN_ORDER_USD and excess > MIN_ORDER_USD:
            # Trim to fund new buys
            trim_amt = min(excess, remaining_gap)
            sells.append((ticker, trim_amt))
            remaining_gap -= trim_amt
            log.info(f"  {ticker}: TRIM ${trim_amt:,.2f} to fund new buys")
        elif abs(drift_pct) > DRIFT_THRESHOLD:
            # Normal drift rebalance — no new buys to fund
            delta = current_val - target
            if delta > MIN_ORDER_USD:
                sells.append((ticker, delta))
                log.info(f"  {ticker}: TRIM ${delta:,.2f} (drift {drift_pct:+.1%})")
            elif delta < -MIN_ORDER_USD:
                buys.append((ticker, abs(delta)))
                log.info(f"  {ticker}: TOP UP ${abs(delta):,.2f} (drift {drift_pct:+.1%})")
        else:
            log.info(f"  {ticker}: HOLD (drift {drift_pct:+.1%} within ±{DRIFT_THRESHOLD:.0%})")

    return sells, buys


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    now = datetime.now(timezone.utc)
    log.info("=" * 52)
    log.info(f"DMG Capital Executor — {MODE} mode")
    log.info(f"Time: {now.isoformat()}")
    log.info("=" * 52)

    if LIVE:
        log.warning("⚠ LIVE MODE — real orders will be placed")
        confirm = input("Type YES to continue: ")
        if confirm.strip() != "YES":
            log.info("Aborted.")
            return

    # 1. Fetch signals
    try:
        portfolio = fetch_signals()
    except Exception as e:
        log.error(f"Failed to fetch signals: {e}")
        sys.exit(1)

    signals     = portfolio.get("current_signals", {})
    btc_signal  = signals.get("BTC", "SELL")
    paxg_signal = signals.get("PAXG", "SELL")
    generated   = portfolio.get("generated", "unknown")

    log.info(f"Signals from: {generated}")
    log.info(f"BTC gate:     {btc_signal}")
    log.info(f"PAXG signal:  {paxg_signal}")

    # ── 2. Determine target allocation via BTC gate ───────────────────────────
    if btc_signal == "BUY":
        # Gate OPEN — equal weight all BUY signals (excl PAXG which is defensive only)
        target_tickers = sorted([
            t for t, s in signals.items()
            if s == "BUY" and t != "PAXG"
        ])
        defensive = None
        log.info(f"Gate OPEN  — target: {', '.join(target_tickers)}")
    else:
        # Gate CLOSED — BTC weekly signal is SELL
        # Move entirely to PAXG (gold) if PAXG is in BUY, otherwise USDT (cash)
        if paxg_signal == "BUY":
            target_tickers = ["PAXG"]
            defensive = "PAXG"
            log.info("Gate CLOSED — defensive: PAXG (gold)")
        else:
            target_tickers = []
            defensive = "USDT"
            log.info("Gate CLOSED — defensive: USDT (cash)")

    # 3. Restore paper state, get balances
    if not LIVE:
        restore_paper_state()

    try:
        balances = get_balances()
        total    = get_total_balance(balances)
        log.info(f"Current balance: ${total:,.2f}")
        for t, v in sorted(balances.items()):
            pct = v / total * 100
            log.info(f"  {t}: ${v:,.2f} ({pct:.1f}%)")
    except Exception as e:
        log.error(f"Failed to get balances: {e}")
        sys.exit(1)

    if total < MIN_ORDER_USD:
        log.error(f"Total balance ${total:.2f} below minimum ${MIN_ORDER_USD}")
        sys.exit(1)

    # 4. Compute rebalance
    if not target_tickers:
        # Defensive: USDT — sell everything
        sells = [(t, v) for t, v in balances.items() if t != "USD" and v > MIN_ORDER_USD]
        buys  = []
        if sells:
            log.info(f"Moving to USDT — selling {len(sells)} position(s)")
        else:
            log.info("Already in USDT — no trades needed")
    else:
        sells, buys = compute_rebalance(balances, target_tickers, total)

    if not sells and not buys:
        log.info("✓ Portfolio already matches target — no trades needed")
        if not LIVE:
            backup_paper_state()
        _log_execution(now, signals, target_tickers, defensive, [], [], total, "NO_CHANGE")
        return

    log.info(f"Plan: {len(sells)} sell(s), {len(buys)} buy(s)")

    # 5. Execute sells first
    sell_results = []
    for ticker, usd_val in sells:
        try:
            result = place_sell(ticker, usd_val)
            sell_results.append({"ticker": ticker, "usd": round(usd_val, 2), "status": "ok"})
            time.sleep(SLEEP_BETWEEN)
        except Exception as e:
            log.error(f"  SELL {ticker} failed: {e}")
            sell_results.append({"ticker": ticker, "usd": round(usd_val, 2), "status": "error", "error": str(e)})

    # Wait for sells to settle
    if sells:
        log.info("Waiting 3s for sells to settle...")
        time.sleep(3)

    # 6. Refresh balance after sells
    try:
        balances = get_balances()
        total    = get_total_balance(balances)
        log.info(f"Post-sell balance: ${total:,.2f}")
    except Exception as e:
        log.warning(f"Could not refresh balance: {e}")

    # 7. Execute buys using exact amounts from compute_rebalance
    buy_results = []
    for ticker, usd_amt in buys:
        if usd_amt < MIN_ORDER_USD:
            log.warning(f"  Skipping {ticker} — ${usd_amt:.2f} below minimum")
            continue
        try:
            result = place_buy(ticker, usd_amt)
            buy_results.append({"ticker": ticker, "usd": round(usd_amt, 2), "status": "ok"})
            time.sleep(SLEEP_BETWEEN)
        except Exception as e:
            log.error(f"  BUY {ticker} failed: {e}")
            buy_results.append({"ticker": ticker, "usd": round(usd_amt, 2), "status": "error", "error": str(e)})

    # 8. Backup paper state
    if not LIVE:
        backup_paper_state()

    # 9. Summary
    log.info("=" * 52)
    log.info("Execution complete")
    log.info(f"  Sells: {sum(1 for r in sell_results if r['status']=='ok')}/{len(sell_results)}")
    log.info(f"  Buys:  {sum(1 for r in buy_results  if r['status']=='ok')}/{len(buy_results)}")
    log.info("=" * 52)

    _log_execution(now, signals, target_tickers, defensive,
                   sell_results, buy_results, total, "EXECUTED")


def _log_execution(now, signals, target, defensive, sells, buys, total, status):
    entry = {
        "timestamp":      now.isoformat(),
        "mode":           MODE,
        "status":         status,
        "btc_signal":     signals.get("BTC"),
        "paxg_signal":    signals.get("PAXG"),
        "defensive":      defensive,
        "target_tickers": target,
        "total_usd":      round(total, 2),
        "sells":          sells,
        "buys":           buys,
    }
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")
    log.info(f"✓ Logged to {LOG_FILE}")


if __name__ == "__main__":
    main()
